# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(20, 30, 101, 31))
        self.label_name.setObjectName("label_name")
        self.label_scores = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_scores.setGeometry(QtCore.QRect(20, 100, 111, 31))
        self.label_scores.setObjectName("label_scores")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(140, 40, 113, 22))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_scores = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_scores.setGeometry(QtCore.QRect(140, 100, 113, 22))
        self.lineEdit_scores.setObjectName("lineEdit_scores")
        self.label_test1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_test1.setGeometry(QtCore.QRect(90, 210, 81, 21))
        self.label_test1.setObjectName("label_test1")
        self.label_test2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_test2.setGeometry(QtCore.QRect(90, 260, 101, 31))
        self.label_test2.setObjectName("label_test2")
        self.label_Test4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Test4.setGeometry(QtCore.QRect(90, 360, 101, 31))
        self.label_Test4.setObjectName("label_Test4")
        self.label_test3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_test3.setGeometry(QtCore.QRect(90, 310, 101, 31))
        self.label_test3.setObjectName("label_test3")
        self.lineEdit_test1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_test1.setGeometry(QtCore.QRect(170, 210, 113, 22))
        self.lineEdit_test1.setObjectName("lineEdit_test1")
        self.lineEdit_test2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_test2.setGeometry(QtCore.QRect(170, 260, 113, 22))
        self.lineEdit_test2.setObjectName("lineEdit_test2")
        self.lineEdit_test3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_test3.setGeometry(QtCore.QRect(170, 310, 113, 22))
        self.lineEdit_test3.setObjectName("lineEdit_test3")
        self.lineEdit_test4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_test4.setGeometry(QtCore.QRect(170, 360, 113, 22))
        self.lineEdit_test4.setObjectName("lineEdit_test4")
        self.pushButton_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_submit.setGeometry(QtCore.QRect(260, 420, 251, 81))
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.label_submitted = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_submitted.setGeometry(QtCore.QRect(310, 510, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_submitted.setFont(font)
        self.label_submitted.setObjectName("label_submitted")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grades"))
        self.label_name.setText(_translate("MainWindow", "Student Name:"))
        self.label_scores.setText(_translate("MainWindow", "Number of tests:"))
        self.label_test1.setText(_translate("MainWindow", "Test 1:"))
        self.label_test2.setText(_translate("MainWindow", "Test 2:"))
        self.label_Test4.setText(_translate("MainWindow", "Test 4:"))
        self.label_test3.setText(_translate("MainWindow", "Test 3:"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.label_submitted.setText(_translate("MainWindow", "SUBMITTED"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
